export type PlaygroundStatus = "ready" | "placeholder"

export type PlaygroundEntry = {
  slug: string
  title: string
  description: string
  href: string
  status: PlaygroundStatus
}

export const foundationEntries: PlaygroundEntry[] = [
  {
    slug: "colors",
    title: "Colors",
    description:
      "Palette and semantic tokens in use. Press p to switch preset and d for light or dark.",
    href: "/foundations/colors",
    status: "ready",
  },
  {
    slug: "typography",
    title: "Typography",
    description:
      "Desktop type COSS primitives use, smallest to biggest. Stock COSS faces and weights sit beside the rendered sample.",
    href: "/foundations/typography",
    status: "ready",
  },
  {
    slug: "inline-heights",
    title: "Inline heights",
    description:
      "Default-size controls that can sit on the same row. Measured height is shown under each sample.",
    href: "/foundations/inline-heights",
    status: "ready",
  },
  {
    slug: "border-radii",
    title: "Border Radii",
    description:
      "Columns are radius steps. Each control sits in the column it uses. Empty cells stay empty.",
    href: "/foundations/border-radii",
    status: "ready",
  },
  {
    slug: "sizes",
    title: "Sizes",
    description:
      "Compare inline controls by desktop height. Token names are captions under each sample.",
    href: "/foundations/sizes",
    status: "ready",
  },
]

export const componentEntries: PlaygroundEntry[] = [
  {
    slug: "accordion",
    title: "Accordion",
    description: "Expandable sections for FAQs and nested content.",
    href: "/components/accordion",
    status: "ready",
  },
  {
    slug: "alert",
    title: "Alert",
    description: "Inline status messages with semantic variants.",
    href: "/components/alert",
    status: "ready",
  },
  {
    slug: "alert-dialog",
    title: "Alert dialog",
    description: "Confirmation modal for destructive actions.",
    href: "/components/alert-dialog",
    status: "ready",
  },
  {
    slug: "autocomplete",
    title: "Autocomplete",
    description: "Searchable combobox with filtered suggestions.",
    href: "/components/autocomplete",
    status: "ready",
  },
  {
    slug: "avatar",
    title: "Avatar",
    description: "Image with fallback initials, sizes, and stacked groups.",
    href: "/components/avatar",
    status: "ready",
  },
  {
    slug: "badges",
    title: "Badges",
    description: "Variants, sizes, icons, and composition patterns.",
    href: "/components/badges",
    status: "ready",
  },
  {
    slug: "breadcrumb",
    title: "Breadcrumb",
    description: "Hierarchy trails with ellipsis, icons, and custom separators.",
    href: "/components/breadcrumb",
    status: "ready",
  },
  {
    slug: "button",
    title: "Button",
    description: "Variants, sizes, icons, loading, and composition patterns.",
    href: "/components/button",
    status: "ready",
  },
  {
    slug: "calendar",
    title: "Calendar",
    description: "Date picker grid built on react-day-picker.",
    href: "/components/calendar",
    status: "ready",
  },
  {
    slug: "card",
    title: "Card",
    description: "Structured surface with header, panel, footer, and action slots.",
    href: "/components/card",
    status: "ready",
  },
  {
    slug: "checkbox",
    title: "Checkbox",
    description: "Single boolean controls with linked labels and disabled state.",
    href: "/components/checkbox",
    status: "ready",
  },
  {
    slug: "checkbox-group",
    title: "Checkbox group",
    description: "Multi-select options grouped inside a fieldset.",
    href: "/components/checkbox-group",
    status: "ready",
  },
  {
    slug: "collapsible",
    title: "Collapsible",
    description: "Progressive disclosure for optional content.",
    href: "/components/collapsible",
    status: "ready",
  },
  {
    slug: "combobox",
    title: "Combobox",
    description: "Searchable selection with filtered suggestions.",
    href: "/components/combobox",
    status: "ready",
  },
  {
    slug: "command",
    title: "Command",
    description: "Keyboard-navigable command palette in a dialog overlay.",
    href: "/components/command",
    status: "ready",
  },
  {
    slug: "context-menu",
    title: "Context menu",
    description: "A menu that opens at the pointer.",
    href: "/components/context-menu",
    status: "ready",
  },
  {
    slug: "date-picker",
    title: "Date picker",
    description: "A calendar inside a popover.",
    href: "/components/date-picker",
    status: "ready",
  },
  {
    slug: "dialog",
    title: "Dialog",
    description: "Modal with a heading and optional footer actions.",
    href: "/components/dialog",
    status: "ready",
  },
  {
    slug: "drawer",
    title: "Drawer",
    description: "A panel that slides in from an edge.",
    href: "/components/drawer",
    status: "ready",
  },
  {
    slug: "empty",
    title: "Empty",
    description: "An empty state with a title and an action.",
    href: "/components/empty",
    status: "ready",
  },
  {
    slug: "field",
    title: "Field",
    description: "A label, description, and error around a control.",
    href: "/components/field",
    status: "ready",
  },
  {
    slug: "fieldset",
    title: "Fieldset",
    description: "A legend around related fields.",
    href: "/components/fieldset",
    status: "ready",
  },
  {
    slug: "form",
    title: "Form",
    description: "A form with native validity messages.",
    href: "/components/form",
    status: "ready",
  },
  {
    slug: "frame",
    title: "Frame",
    description: "A framed header, panel, and footer.",
    href: "/components/frame",
    status: "ready",
  },
  {
    slug: "group",
    title: "Group",
    description: "Connected controls that share one outline.",
    href: "/components/group",
    status: "ready",
  },
  {
    slug: "input-groups",
    title: "Input groups",
    description: "Inputs with inline addons for icons, prefixes, and suffixes.",
    href: "/components/input-groups",
    status: "ready",
  },
  {
    slug: "kbd",
    title: "Kbd",
    description: "Keyboard keys and shortcut chords.",
    href: "/components/kbd",
    status: "ready",
  },
  {
    slug: "label",
    title: "Label",
    description: "An accessible name for a control.",
    href: "/components/label",
    status: "ready",
  },
  {
    slug: "menu",
    title: "Menu",
    description: "A dropdown of actions, shortcuts, and checkbox items.",
    href: "/components/menu",
    status: "ready",
  },
  {
    slug: "meter",
    title: "Meter",
    description: "A known quantity inside a range.",
    href: "/components/meter",
    status: "ready",
  },
  {
    slug: "number-field",
    title: "Number field",
    description: "Stepped numeric input with increment controls and sizes.",
    href: "/components/number-field",
    status: "ready",
  },
  {
    slug: "otp-field",
    title: "OTP field",
    description: "A segmented code with an optional separator.",
    href: "/components/otp-field",
    status: "ready",
  },
  {
    slug: "pagination",
    title: "Pagination",
    description: "Page links, or previous and next only.",
    href: "/components/pagination",
    status: "ready",
  },
  {
    slug: "popover",
    title: "Popover",
    description: "A floating panel anchored to a button.",
    href: "/components/popover",
    status: "ready",
  },
  {
    slug: "preview-card",
    title: "Preview card",
    description: "A hover preview on a link.",
    href: "/components/preview-card",
    status: "ready",
  },
  {
    slug: "progress",
    title: "Progress",
    description: "Partial, complete, and indeterminate task status.",
    href: "/components/progress",
    status: "ready",
  },
  {
    slug: "radio",
    title: "Radio",
    description: "Single-choice groups with linked labels and disabled options.",
    href: "/components/radio",
    status: "ready",
  },
  {
    slug: "scroll-area",
    title: "Scroll area",
    description: "A bounded list with a styled scrollbar.",
    href: "/components/scroll-area",
    status: "ready",
  },
  {
    slug: "select",
    title: "Select",
    description: "Popup selection with sizes, disabled items, and a disabled trigger.",
    href: "/components/select",
    status: "ready",
  },
  {
    slug: "separator",
    title: "Separator",
    description: "Horizontal and vertical rules.",
    href: "/components/separator",
    status: "ready",
  },
  {
    slug: "sheet",
    title: "Sheet",
    description: "A dialog docked to an edge.",
    href: "/components/sheet",
    status: "ready",
  },
  {
    slug: "sidebar",
    title: "Sidebar",
    description: "A navigation rail beside page content.",
    href: "/components/sidebar",
    status: "ready",
  },
  {
    slug: "skeleton",
    title: "Skeleton",
    description: "Placeholders for content that is still loading.",
    href: "/components/skeleton",
    status: "ready",
  },
  {
    slug: "slider",
    title: "Slider",
    description: "Continuous values with a value readout and disabled state.",
    href: "/components/slider",
    status: "ready",
  },
  {
    slug: "spinner",
    title: "Spinner",
    description: "An indeterminate loading indicator.",
    href: "/components/spinner",
    status: "ready",
  },
  {
    slug: "switch",
    title: "Switch",
    description: "Immediate on/off preferences with default and disabled states.",
    href: "/components/switch",
    status: "ready",
  },
  {
    slug: "table",
    title: "Table",
    description: "Rows and columns with an optional caption.",
    href: "/components/table",
    status: "ready",
  },
  {
    slug: "tabs",
    title: "Tabs",
    description: "Segmented panels for switching between related views.",
    href: "/components/tabs",
    status: "ready",
  },
  {
    slug: "text-inputs",
    title: "Text inputs",
    description: "Default, sized, disabled, and invalid states with labels and helper text.",
    href: "/components/text-inputs",
    status: "ready",
  },
  {
    slug: "textarea",
    title: "Textarea",
    description: "Multi-line text entry with helper text and invalid state.",
    href: "/components/textarea",
    status: "ready",
  },
  {
    slug: "toast",
    title: "Toast",
    description: "Temporary notices for success, info, warning, and error.",
    href: "/components/toast",
    status: "ready",
  },
  {
    slug: "toggle",
    title: "Toggle",
    description: "A two-state command button.",
    href: "/components/toggle",
    status: "ready",
  },
  {
    slug: "toggle-group",
    title: "Toggle group",
    description: "Related toggles that share a pressed state.",
    href: "/components/toggle-group",
    status: "ready",
  },
  {
    slug: "toolbar",
    title: "Toolbar",
    description: "Formatting toggles and actions on one strip.",
    href: "/components/toolbar",
    status: "ready",
  },
  {
    slug: "tooltip",
    title: "Tooltip",
    description: "A short hint on hover or focus.",
    href: "/components/tooltip",
    status: "ready",
  },
]

export function findFoundation(slug: string): PlaygroundEntry | undefined {
  return foundationEntries.find((entry) => entry.slug === slug)
}

export function findComponent(slug: string): PlaygroundEntry | undefined {
  return componentEntries.find((entry) => entry.slug === slug)
}
